"""
RDF dumper for Pydantic models that uses embedded LinkML metadata.

This dumper works directly with Pydantic models generated by LinkML,
using only the embedded linkml_meta without requiring a SchemaView.

Uses a BFS work-queue to serialize the object graph iteratively,
avoiding infinite recursion on circular references (e.g. evolvesFrom/evolvesTo).
"""

import logging
from collections import deque
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel
from rdflib import XSD, Graph, Namespace, URIRef
from rdflib.namespace import RDF
from rdflib.term import BNode, Literal, Node

from linkml_runtime.dumpers.dumper_root import Dumper

logger = logging.getLogger(__name__)


@dataclass
class PydanticRDFContext:
    """Context for Pydantic RDF conversion using embedded metadata."""

    graph: Graph
    prefixes: dict[str, str]
    global_meta: dict[str, Any]
    to_emit: deque = field(default_factory=deque)
    emitted: set[str] = field(default_factory=set)

    def get_namespace(self, prefix: str) -> Namespace | None:
        """Get namespace for a prefix."""
        if prefix in self.prefixes:
            return Namespace(self.prefixes[prefix])
        return None

    def expand_curie(self, curie_or_uri: str) -> str:
        """Expand a CURIE to full URI."""
        if "://" in curie_or_uri:
            return curie_or_uri
        if ":" in curie_or_uri:
            prefix, local = curie_or_uri.split(":", 1)
            if prefix in self.prefixes:
                return self.prefixes[prefix] + local
        return curie_or_uri


class PydanticRDFDumper(Dumper):
    """
    Dumps Pydantic models to RDF using embedded LinkML metadata.

    Uses a BFS work-queue to serialize the object graph iteratively.
    Named objects (with ``id``) are queued and deduplicated via an
    ``emitted`` set.  BNode objects (no ``id``) are serialized inline
    since they cannot cause cycles.
    """

    def as_rdf_graph(
        self,
        element: BaseModel,
        prefix_map: dict[str, str] | None = None,
    ) -> Graph:
        """
        Convert Pydantic model to RDF Graph using embedded metadata.

        :param element: Pydantic model instance to convert
        :param prefix_map: Optional additional prefix mappings
        :return: RDF Graph
        """
        g = Graph()

        global_meta = self._extract_global_metadata(element)

        prefixes = {}
        if "prefixes" in global_meta:
            for prefix_info in global_meta["prefixes"].values():
                prefixes[prefix_info["prefix_prefix"]] = prefix_info["prefix_reference"]

        if prefix_map:
            prefixes.update(prefix_map)

        for prefix, uri in prefixes.items():
            g.namespace_manager.bind(prefix, URIRef(uri))

        ctx = PydanticRDFContext(graph=g, prefixes=prefixes, global_meta=global_meta)

        # BFS: seed the queue with root element
        ctx.to_emit.append(element)

        while ctx.to_emit:
            obj = ctx.to_emit.popleft()
            uri_str = self._obj_uri_str(obj, ctx)
            if uri_str is not None:
                if uri_str in ctx.emitted:
                    continue
                ctx.emitted.add(uri_str)
            self._emit_object(obj, ctx)

        return g

    # ------------------------------------------------------------------
    # BFS object serialization
    # ------------------------------------------------------------------

    def _obj_uri_str(self, obj: BaseModel, ctx: PydanticRDFContext) -> str | None:
        """Get expanded URI string for an object, or None for BNodes."""
        id_val = getattr(obj, "id", None)
        if id_val:
            return ctx.expand_curie(str(id_val))
        return None

    def _emit_object(self, element: BaseModel, ctx: PydanticRDFContext) -> Node:
        """Emit all triples for a single object. Returns its subject node."""
        class_meta = self._get_class_metadata(element)
        subject_uri = self._create_subject_uri(element, class_meta, ctx)
        self._add_type_triple(subject_uri, class_meta, ctx)

        model_fields = type(element).model_fields
        for field_name, field_info in model_fields.items():
            if field_name == "id":
                continue

            actual_value = getattr(element, field_name)
            if actual_value is None:
                continue

            field_meta = self._get_field_metadata(field_info)
            property_uri = self._get_property_uri(field_meta, field_name, ctx)
            self._emit_value(subject_uri, property_uri, actual_value, ctx)

        return subject_uri

    def _emit_value(self, subject: Node, predicate: URIRef, value: Any, ctx: PydanticRDFContext) -> None:
        """Emit triple(s) for a field value."""
        if isinstance(value, list):
            for item in value:
                self._emit_value(subject, predicate, item, ctx)
        elif isinstance(value, BaseModel):
            uri_str = self._obj_uri_str(value, ctx)
            if uri_str is not None:
                # Named object: emit linking triple, queue for BFS
                child_uri = URIRef(uri_str)
                ctx.graph.add((subject, predicate, child_uri))
                if uri_str not in ctx.emitted:
                    ctx.to_emit.append(value)
            else:
                # BNode: emit inline (cannot cause cycles)
                child_node = self._emit_object(value, ctx)
                ctx.graph.add((subject, predicate, child_node))
        else:
            node = self._to_rdf_literal(value)
            ctx.graph.add((subject, predicate, node))

    # ------------------------------------------------------------------
    # Helpers (unchanged from original)
    # ------------------------------------------------------------------

    def _to_rdf_literal(self, element: Any) -> Node:
        """Convert a Python primitive to an RDF Literal with appropriate datatype."""
        if isinstance(element, bool):
            return Literal(element, datatype=XSD.boolean)
        elif isinstance(element, int):
            return Literal(element, datatype=XSD.integer)
        elif isinstance(element, float):
            return Literal(element, datatype=XSD.decimal)
        else:
            from datetime import date, datetime
            from decimal import Decimal

            if isinstance(element, datetime):
                return Literal(element.isoformat(), datatype=XSD.dateTime)
            elif isinstance(element, date):
                return Literal(element.isoformat(), datatype=XSD.date)
            elif isinstance(element, Decimal):
                return Literal(str(element), datatype=XSD.decimal)
            else:
                return Literal(str(element))

    def _get_class_metadata(self, element: BaseModel) -> dict[str, Any]:
        """Extract class metadata from Pydantic model."""
        element_type = type(element)
        if hasattr(element_type, "linkml_meta"):
            return element_type.linkml_meta.root
        return {"name": element_type.__name__}

    def _create_subject_uri(self, element: BaseModel, class_meta: dict[str, Any], ctx: PydanticRDFContext) -> Node:
        """Create subject URI for the element."""
        id_field = getattr(element, "id", None)
        if id_field:
            expanded_uri = ctx.expand_curie(str(id_field))
            return URIRef(expanded_uri)
        return BNode()

    def _add_type_triple(self, subject_uri: Node, class_meta: dict[str, Any], ctx: PydanticRDFContext) -> None:
        """Add rdf:type triple for the element."""
        class_uri = class_meta.get("class_uri")
        if class_uri:
            expanded_uri = ctx.expand_curie(class_uri)
            ctx.graph.add((subject_uri, RDF.type, URIRef(expanded_uri)))
        else:
            class_name = class_meta.get("name", "Unknown")
            from_schema = class_meta.get("from_schema", "")
            if from_schema:
                class_uri = f"{from_schema}#{class_name}"
            else:
                class_uri = f"#{class_name}"
            ctx.graph.add((subject_uri, RDF.type, URIRef(class_uri)))

    def _get_field_metadata(self, field_info: Any) -> dict[str, Any]:
        """Extract metadata from Pydantic field."""
        if hasattr(field_info, "json_schema_extra") and field_info.json_schema_extra:
            linkml_meta = field_info.json_schema_extra.get("linkml_meta", {})
            return linkml_meta
        return {}

    def _get_property_uri(self, field_meta: dict[str, Any], field_name: str, ctx: PydanticRDFContext) -> URIRef:
        """Get property URI from field metadata."""
        slot_uri = field_meta.get("slot_uri")
        if slot_uri:
            return URIRef(ctx.expand_curie(slot_uri))

        exact_mappings = field_meta.get("exact_mappings", [])
        if exact_mappings:
            return URIRef(ctx.expand_curie(exact_mappings[0]))

        from_schema = field_meta.get("from_schema", "")
        if from_schema:
            if not from_schema.endswith(("/", "#")):
                from_schema += "/"
            return URIRef(from_schema + field_name)

        return URIRef(f"#{field_name}")

    def _extract_global_metadata(self, element: BaseModel) -> dict[str, Any]:
        """Extract global metadata from the model module."""
        try:
            import importlib

            module_obj = importlib.import_module(element.__class__.__module__)
            if hasattr(module_obj, "linkml_meta"):
                return module_obj.linkml_meta.root
        except ImportError:
            pass

        return {}

    # ------------------------------------------------------------------
    # Public API (dump / dumps)
    # ------------------------------------------------------------------

    def dump(
        self,
        element: BaseModel,
        to_file: str,
        fmt: str = "turtle",
        prefix_map: dict[str, str] | None = None,
        **args,
    ) -> None:
        """
        Write element as RDF to file.

        :param element: Pydantic model to convert
        :param to_file: Output file path
        :param fmt: RDF format (turtle, xml, etc.)
        :param prefix_map: Optional prefix mappings
        """
        graph = self.as_rdf_graph(element, prefix_map=prefix_map)
        with open(to_file, "w") as f:
            f.write(graph.serialize(format=fmt))

    def dumps(
        self,
        element: BaseModel,
        fmt: str = "turtle",
        prefix_map: dict[str, str] | None = None,
    ) -> str:
        """
        Convert element to RDF string.

        :param element: Pydantic model to convert
        :param fmt: RDF format (turtle, xml, etc.)
        :param prefix_map: Optional prefix mappings
        :return: RDF string
        """
        graph = self.as_rdf_graph(element, prefix_map=prefix_map)
        return graph.serialize(format=fmt)
