"""Pydantic introspection utilities for LinkML-generated models.

Provides schema-independent introspection using the ``linkml_meta`` metadata
embedded in Pydantic models generated by ``gen-pydantic``.  Unlike
:class:`~linkml_runtime.utils.schemaview.SchemaView`, these functions require
no schema file I/O — they work directly with in-memory Pydantic classes.

Typical usage::

    from linkml_runtime.utils.pydantic_utils import get_class_uri, get_slot_uri

    uri = get_class_uri(MyModel)
    slot = get_slot_uri("my_field", MyModel)
"""

from __future__ import annotations

import importlib
import typing
from types import ModuleType
from urllib.parse import unquote

from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_linkml_meta_root(pydantic_class: type[BaseModel]) -> dict:
    """Return the ``linkml_meta.root`` dict, raising on missing metadata."""
    if not hasattr(pydantic_class, "linkml_meta"):
        raise ValueError(f"Class {pydantic_class.__name__} does not have a linkml_meta attribute")
    return pydantic_class.linkml_meta.root


def _get_prefixes(
    model_or_module: type[BaseModel] | ModuleType | None = None,
) -> dict:
    """Extract embedded prefix map from a model class or its module.

    If *model_or_module* is ``None`` the caller should handle the empty dict.
    """
    if model_or_module is None:
        return {}

    if isinstance(model_or_module, ModuleType):
        meta = getattr(model_or_module, "linkml_meta", None)
        if meta is not None:
            return meta.root.get("prefixes", {})
        return {}

    # Pydantic class — get module-level linkml_meta
    module = importlib.import_module(model_or_module.__module__)
    meta = getattr(module, "linkml_meta", None)
    if meta is not None:
        return meta.root.get("prefixes", {})
    return {}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def is_union_type(pydantic_type: type[BaseModel]) -> bool:
    """Check whether a Pydantic model represents a LinkML union type.

    Detects both ``typing.Union`` origins and the ``union_of`` key in
    ``linkml_meta``.
    """
    if typing.get_origin(pydantic_type) is typing.Union:
        return True
    if hasattr(pydantic_type, "linkml_meta") and hasattr(pydantic_type.linkml_meta, "root"):
        return bool(pydantic_type.linkml_meta.root.get("union_of"))
    return False


def expand_curie(
    curie: str,
    model_or_module: type[BaseModel] | ModuleType | None = None,
    *,
    fallback_schema: str | None = None,
) -> str:
    """Expand a CURIE to a full URI using embedded LinkML prefix definitions.

    Parameters
    ----------
    curie:
        A CURIE (e.g. ``"pokemon:hasWeight"``) or already-expanded URI.
    model_or_module:
        A Pydantic model class or the module containing ``linkml_meta``.
        Used to look up the prefix map.  When ``None``, only the
        *fallback_schema* is used.
    fallback_schema:
        Schema URI used when the prefix is not found in the prefix map
        (produces ``{fallback_schema}#{local}``).

    Returns
    -------
    str
        The expanded URI, or the input unchanged if it is already a full URI.
    """
    if "://" in curie:
        return curie

    if ":" not in curie:
        return curie

    prefix, local = curie.split(":", 1)

    prefixes = _get_prefixes(model_or_module)
    if prefix in prefixes:
        prefix_ref = prefixes[prefix].get("prefix_reference", "")
        return f"{prefix_ref}{local}"

    if fallback_schema:
        return f"{fallback_schema}#{local}"

    return curie


def get_class_uri(
    pydantic_class: type[BaseModel],
    model_or_module: type[BaseModel] | ModuleType | None = None,
) -> str:
    """Extract the RDF class URI from a Pydantic model's ``linkml_meta``.

    Handles percent-encoded URIs (from generated models) by decoding them.
    Falls back to ``{from_schema}#{ClassName}`` when no explicit
    ``class_uri`` is present.

    Parameters
    ----------
    pydantic_class:
        A Pydantic model class with a ``linkml_meta`` attribute.
    model_or_module:
        Optional model or module for CURIE expansion.  When ``None`` the
        class's own module is used.
    """
    meta = _get_linkml_meta_root(pydantic_class)
    class_uri = meta.get("class_uri")
    from_schema = meta.get("from_schema")

    source = model_or_module if model_or_module is not None else pydantic_class

    if class_uri:
        return unquote(expand_curie(class_uri, source, fallback_schema=from_schema))

    if from_schema:
        return f"{from_schema}#{pydantic_class.__name__}"

    raise ValueError(f"Class {pydantic_class.__name__} has no class_uri or from_schema in linkml_meta")


def get_parent_classes(
    pydantic_class: type[BaseModel],
) -> list[type[BaseModel]]:
    """Return parent classes that carry ``linkml_meta``, via Python MRO.

    Excludes the class itself, ``BaseModel``, and ``object``.
    """
    return [cls for cls in pydantic_class.__mro__[1:] if hasattr(cls, "linkml_meta")]


def get_direct_subclasses(
    pydantic_class: type[BaseModel],
    all_classes: list[type[BaseModel]],
) -> list[type[BaseModel]]:
    """Return direct subclasses of *pydantic_class* found in *all_classes*.

    Only classes whose ``__bases__`` include *pydantic_class* are returned
    (grandchildren are excluded).
    """
    return [
        cls
        for cls in all_classes
        if (cls != pydantic_class and issubclass(cls, pydantic_class) and pydantic_class in cls.__bases__)
    ]


def collect_all_type_uris(
    pydantic_type: type[BaseModel],
    *,
    include_subclasses: bool = True,
    all_classes: list[type[BaseModel]] | None = None,
    model_or_module: type[BaseModel] | ModuleType | None = None,
    _visited: set[str] | None = None,
) -> set[str]:
    """Recursively collect all class URIs for a type hierarchy.

    Supports inheritance hierarchies, ``typing.Union``, and LinkML
    ``union_of`` metadata.

    Parameters
    ----------
    pydantic_type:
        Root type to start collecting from.
    include_subclasses:
        When ``True``, also collects URIs for subclasses.
    all_classes:
        Complete list of available Pydantic classes (needed for
        subclass and forward-ref resolution).
    model_or_module:
        Model or module for CURIE expansion.
    """
    if _visited is None:
        _visited = set()

    if is_union_type(pydantic_type):
        union_args = typing.get_args(pydantic_type)
        if not union_args and hasattr(pydantic_type, "linkml_meta"):
            union_of = pydantic_type.linkml_meta.root.get("union_of", [])
            module = importlib.import_module(pydantic_type.__module__)
            union_args = tuple(getattr(module, name) for name in union_of if hasattr(module, name))

        result: set[str] = set()
        for member in union_args:
            if member is not type(None):
                if hasattr(member, "__forward_arg__"):
                    member = _resolve_forward_ref(member, all_classes)
                    if member is None:
                        continue
                result.update(
                    collect_all_type_uris(
                        member,
                        include_subclasses=include_subclasses,
                        all_classes=all_classes,
                        model_or_module=model_or_module,
                        _visited=_visited,
                    )
                )
        return result

    class_name = pydantic_type.__name__
    if class_name in _visited:
        return set()
    _visited.add(class_name)

    uris: set[str] = set()
    try:
        uris.add(get_class_uri(pydantic_type, model_or_module))
    except ValueError:
        # Abstract mixins or base classes may lack class_uri/from_schema —
        # skip them and continue collecting from concrete subclasses.
        pass

    if include_subclasses and all_classes:
        for sub in get_direct_subclasses(pydantic_type, all_classes):
            uris.update(
                collect_all_type_uris(
                    sub,
                    include_subclasses=include_subclasses,
                    all_classes=all_classes,
                    model_or_module=model_or_module,
                    _visited=_visited,
                )
            )

    return {u for u in uris if u}


def is_quantity_field(
    model_type: type[BaseModel],
    field_name: str,
    *,
    quantity_class_uri: str = "qudt:Quantity",
) -> bool:
    """Check whether a field's annotation resolves to a quantity type.

    Parameters
    ----------
    model_type:
        Pydantic model class containing the field.
    field_name:
        Name of the field to check.
    quantity_class_uri:
        Expected ``class_uri`` value in the field type's ``linkml_meta``
        (default ``"qudt:Quantity"``).
    """
    if field_name not in model_type.model_fields:
        return False
    annotation = model_type.model_fields[field_name].annotation
    args = typing.get_args(annotation)
    if args:
        inner = [a for a in args if a is not type(None)]
        if len(inner) == 1:
            annotation = inner[0]
    return (
        isinstance(annotation, type)
        and hasattr(annotation, "linkml_meta")
        and annotation.linkml_meta.root.get("class_uri") == quantity_class_uri
    )


def get_slot_uri(
    field_name: str,
    pydantic_type: type[BaseModel],
    model_or_module: type[BaseModel] | ModuleType | None = None,
) -> str:
    """Extract the RDF predicate URI for a Pydantic field.

    Resolution order:

    1. Explicit ``slot_uri`` in the field's ``linkml_meta``.
    2. Fallback: ``{from_schema}#{slot_name}``.

    Parameters
    ----------
    field_name:
        Name of the Pydantic field.
    pydantic_type:
        Model class containing the field.
    model_or_module:
        Optional model or module for CURIE expansion.
    """
    if not (hasattr(pydantic_type, "model_fields") and field_name in pydantic_type.model_fields):
        raise ValueError(f"Field {field_name} not found in {pydantic_type.__name__}")

    field_info = pydantic_type.model_fields[field_name]

    if not (hasattr(field_info, "json_schema_extra") and isinstance(field_info.json_schema_extra, dict)):
        raise ValueError(f"Field {field_name} in {pydantic_type.__name__} has no json_schema_extra")

    meta = field_info.json_schema_extra.get("linkml_meta", {})
    if not isinstance(meta, dict):
        meta = {}

    slot_uri = meta.get("slot_uri")
    if isinstance(slot_uri, str):
        source = model_or_module if model_or_module is not None else pydantic_type
        return expand_curie(slot_uri, source, fallback_schema=meta.get("from_schema"))

    from_schema = meta.get("from_schema")
    slot_name = meta.get("name", field_name)
    if isinstance(from_schema, str):
        return f"{from_schema}#{slot_name}"

    raise ValueError(f"Field {field_name} in {pydantic_type.__name__} has no slot_uri or from_schema")


def reverse_lookup_model(
    class_uri: str,
    all_classes: list[type[BaseModel]],
    model_or_module: type[BaseModel] | ModuleType | None = None,
) -> type[BaseModel]:
    """Find the Pydantic model class corresponding to a given class URI.

    Parameters
    ----------
    class_uri:
        Full RDF class URI to look up.
    all_classes:
        List of candidate Pydantic model classes to search.
    model_or_module:
        Optional model or module for CURIE expansion during lookup.

    Raises
    ------
    ValueError
        If no model matches the URI.
    """
    for cls in all_classes:
        try:
            if get_class_uri(cls, model_or_module) == class_uri:
                return cls
        except ValueError:
            continue
    raise ValueError(f"No Pydantic model found for class URI: {class_uri!r}")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _resolve_forward_ref(
    ref: typing.ForwardRef,
    all_classes: list[type[BaseModel]] | None,
) -> type[BaseModel] | None:
    """Resolve a ``ForwardRef`` to a class from *all_classes*."""
    if not all_classes:
        return None
    name = ref.__forward_arg__
    return next((cls for cls in all_classes if cls.__name__ == name), None)
